 final List<Map<String, dynamic>> doaHarianList = [
      {
        'title': 'Doa Sebelum Belajar ',
        'text': 'Allahumma infa nii bimaa allamtanii wa allimnii maa yanfa uunii. Allahumma innii as aluka fahmal-nabiyyiin wa hifzal mursaliin. Waqalbalsy syuhadaa i, wa aynalsiddiiqiin, wa amalan shoolihin. Ya muqallibalquluub thabbit qalbii alaa diinika.',
        'artinya': 'Ya Allah, manfaatkanlah aku dengan apa yang telah Engkau ajarkan padaku dan ajarkanlah aku hal-hal yang bermanfaat bagiku. Ya Allah, aku mohon kepada-Mu pemahaman para nabi, perlindungan para rasul, hati para syuhada, mata hati para siddiqin, dan amal perbuatan orang-orang shalih. Wahai Tuhan yang membolak-balikkan hati, tetapkan hatiku dalam agamamu.',
        'imageAsset': 'assets/images/belajar.jpg', 
      },
      {
        'title': 'Doa Ketika Angin Kencang',
        'text': 'Allahumma inii as-aluka khoyrahaa wa khoyra maa feehaa wa khoyra maa ur-silat bihi',
        'artinya': 'Ya Allah, aku memohon kepada-Mu kebaikan angin ini, kebaikan yang ada di dalamnya, dan kebaikan yang diutus dengannya.',
        'imageAsset': 'assets/images/angin.jpg', 
      },
      {
        'title': 'Doa Ketika Melihat Gerhana Matahari atau Bulan',
        'text': 'Subhaanallahi walhamdulillahi walaa ilaaha illallah wallahu akbar.',
        'artinya': 'Maha Suci Allah, segala puji bagi Allah, tidak ada tuhan selain Allah, Allah Maha Besar.',
        'imageAsset': 'assets/images/gerhana.jpg', 
      },
      {
        'title': 'Doa Bangun Tidur',
        'text': 'Alhamdulillahillazi ahyana ba’da ma amatana wa ilaihi nusyur...',
        'artinya': 'Segala puji bagi Allah yang menghidupkan kita setelah Dia mematikan kita dan hanya kepada-Nya kita akan dibangkitkan.',
        'imageAsset': 'assets/images/bangunTidur.jpg', 
      },
      {
        'title': 'Doa Sebelum Tidur',
        'text': 'Bismika allahumma amutu wa ahya',
        'artinya': 'Dengan nama-Mu, ya Allah, aku mati dan aku hidup.',
        'imageAsset': 'assets/images/sebelumtidur.jpg', 
      },
      {
        'title': 'Doa Masuk Kamar Mandi',
        'text': 'Allahumma inni a udhu bika minal khubutsi wal khaba-itsi',
        'artinya': 'Ya Allah, aku berlindung pada-Mu dari (gangguan) jin laki-laki dan jin perempuan.',
        'imageAsset': 'assets/images/masukKM.jpg', 
      },
      {
        'title': 'Doa Keluar Kamar Mandi',
        'text': 'Ghufranak',
        'artinya': 'Aku memohon ampunan-Mu.',
        'imageAsset': 'assets/images/keluarKM.jpg', 
      },
      {
        'title': 'Doa Memakai Baju Baru',
        'text': 'Alhamdulillahillazi kasaani ma uwari bihi ‘awrati wa atajammalu bihi fi hayaati',
        'artinya': 'Segala puji bagi Allah yang telah memberi aku pakaian yang dapat menutupi auratku dan membuatku tampak indah dalam hidupku.',
        'imageAsset': 'assets/images/berpakaian.jpg', 
      },
      {
        'title': 'Doa Ketika Bercermin',
        'text': 'Allahumma anta hasanta khalqi fa hasin khuluqi',
        'artinya': 'Ya Allah, Engkau telah menciptakan makhluk-Mu dengan sebaik-baik ciptaan, maka perbaikilah akhlakku',
        'imageAsset': 'assets/images/bercermin.jpg', 
      },
      {
        'title': 'Doa Sebelum Makan',
        'text': 'Allahumma baariklana fiima rozaktana waqina adzabannar',
        'artinya': 'Dengan menyebut nama Allah.',
        'imageAsset': 'assets/images/makan.jpg', 
      },
      {
        'title': 'Doa Setelah Makan',
        'text': 'Alhamdulillahil ladhi at’amana wa saqana wa ja’alana minal muslimin',
        'artinya': 'Segala puji bagi Allah yang memberi kami makan dan minum, serta menjadikan kami termasuk orang-orang yang berserah diri.',
        'imageAsset': 'assets/images/makan.jpg', 
      },
      {
        'title': 'Doa Masuk Rumah',
        'text': 'Bismillahi walajna, bismillahi kharajna, wa alaa rabbina tawakkalna',
        'artinya': 'Dengan menyebut nama Allah kami masuk, dengan menyebut nama Allah kami keluar, dan kepada Allah kami bertawakkal.',
        'imageAsset': 'assets/images/keluarrumah.jpg', 
      },
      {
        'title': 'Doa Keluar Rumah',
        'text': 'Bismillahi tawakkaltu alallah, laa hawla wa laa quwwata illa billah',
        'artinya': 'Dengan menyebut nama Allah, aku bertawakal kepada-Nya, tidak ada daya dan upaya kecuali dengan pertolongan Allah.',
        'imageAsset': 'assets/images/keluarrumah.jpg', 
      },
      {
        'title': 'Doa Ketika Mendengar Petir',
        'text': 'Subhanallahil ladhi yusabbihur ra du bihamdihi wal mala ikatu min kheefatihi',
        'artinya': 'Maha suci Allah yang petir bertasbih dengan memuji-Nya, dan para malaikat juga kagum dengan ketakutannya.',
        'imageAsset': 'assets/images/petir.jpg', 
      },
      {
        'title': 'Doa Ketika Turun Hujan ',
        'text': 'Allahumma sayyiban naafi  a',
        'artinya': 'Ya Allah, hujan yang bermanfaat',
        'imageAsset': 'assets/images/hujan.jpg', 
      },
      {
        'title': 'Doa Ketika Sakit ',
        'text': 'As alullaha azza wa jalla, alladzi laa ilaaha illaa huwal hayyal qayyum, ann yashfiyaka',
        'artinya': 'Aku memohon kepada Allah yang tiada Tuhan selain-Nya, yang Maha Hidup dan Maha Kekal, semoga Dia menyembuhkanmu',
        'imageAsset': 'assets/images/sakit.jpg', 
      },
      {
        'title': 'Doa Ketika Mendengar Adzan',
        'text': 'Ashhadu alla ilaha illallah, wa ashhadu anna Muhammadur Rasulullah',
        'artinya': 'Aku bersaksi bahwa tiada Tuhan selain Allah, dan aku bersaksi bahwa Muhammad adalah Rasulullah.',
        'imageAsset': 'assets/images/adzan.jpg', 
      },
    ];